# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/setup.md
fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    serializer:
        serializer: jms_serializer
    indexes:
        articles:
            client: default
            types:
                _doc:
                    properties:
                        documentId: ~
                        documentDesc: { boost: 10, analyzer: elastica-analyzer}
                        documentDate: ~
                        documentType: ~
        my-store:
            client: default
            types:
                docs:
                    properties:
                        primaryKey: ~
                        dsPk: ~
                        documentDesc: ~
                        documentDt: ~
                        protocolNumb: ~
                        user: ~
                        documentTypeId: ~
                        documentTypeName: ~
                        systemId: ~



